--1--Hallar el salario medio, el mínimo, el máximo, 
--para el colectivo formado por todos los empleados
SELECT ALL  MAX(SALARIO) AS MAXIMO,
            MIN(SALARIO) AS MINIMO,
            ROUND(MEDIAN(SALARIO),2) AS MEDIANA
FROM EMPLEADOS
;

SELECT ALL SALARIO
FROM EMPLEADOS
GROUP BY AVG;
--2 Obtener por orden alfabético los salarios y los nombres de los empleados 
--cuyo salario es mayor que el
--60% del máximo.
SELECT ALL SALARIO,NOMEMP
FROM EMPLEADOS
WHERE SALARIO > (SELECT MAX(SALARIO)*0.6 FROM EMPLEADOS)
;

--3
SELECT ALL MAX(TRUNC(MONTHS_BETWEEN(SYSDATE,fechanac)/12)) EDAD
FROM EMPLEADOS
WHERE numdep=110;

SELECT ALL TRUNC(MONTHS_BETWEEN(SYSDATE,MIN(fechanac))/12) EDAD
FROM EMPLEADOS
WHERE numdep=110;

--4
SELECT ALL  COUNT(*) AS "numero de empleados",
            SUM(COMISION) AS "suma",
            AVG(NVL(COMISION,0)) AS "media"
FROM EMPLEADOS
WHERE NUMDEP=112;

--5
SELECT ALL TRUNC(AVG(TRUNC(MONTHS_BETWEEN(SYSDATE,FECHANAC)/12))) AS "media edad"
FROM EMPLEADOS
WHERE NUMDEP= 100;

--6
SELECT ALL  COUNT(NUMDEP) AS "departamentos",
            AVG(PRESUP) AS "presupuesto medio"
FROM DEPARTAMENTOS;

--7
SELECT ALL ROUND(AVG(TRUNC(MONTHS_BETWEEN(TO_DATE('31/12/2000','dd/mm/yyyy'),FECHAING)/12)),1) as años
FROM EMPLEADOS
WHERE NUMDEP IN(111,112);

--8
SELECT ALL NUMEMP,NOMEMP,SALARIO+NVL(COMISION,0)"SALARIO TOTAL"
FROM EMPLEADOS
WHERE SALARIO+NVL(COMISION,0)>(SELECT MIN(SALARIO) + 1500 FROM EMPLEADOS)
ORDER BY NUMEMP ASC;

--9
SELECT ALL COUNT(NUMEMP) AS empleados
FROM EMPLEADOS
WHERE TO_CHAR(FECHAING,'YYYY')=2000;

SELECT ALL COUNT(NUMEMP) AS empleados
FROM EMPLEADOS
WHERE EXTRACT(YEAR FROM FECHAING)=2000;

SELECT COUNT(*) empleados
FROM EMPLEADOS
WHERE TO_CHAR(FECHAING,'YY')=00;

--10
SELECT ALL AVG(SALARIO) AS "salario medio"
FROM EMPLEADOS
WHERE SALARIO <= 1.2*(SELECT MIN(SALARIO) FROM EMPLEADOS WHERE NUMHIJOS>0);

--11
SELECT ALL MAX(salario) - MIN(salario) AS diferencia
FROM empleados;